export const API_ROUTES = {
    CREATE_COMPANY: "/admin/companyRegistration",
    GET_COMPANIES: "/admin/companies",
    VIEW_ALL_COMPANIES: "/admin/viewAllCompanies",
    FILE_EXPORT_UPLOADS: {
        activation: "/import/activationDetailReport",
        saleDetail: "/import/saleDetailReport",
        callidus: "/import/callidusReport",
        retentionReport: "/import/retentionReport",
    },
    LAST_UPLOADED_REPORTS: "/import/lastUploadedReportsForCompany",
    VIEW_REBATES: "/import/viewRebates",
    RETENTION_COMPANY: "/import/accounts/92-days-ago",
    RETENTION_STORE: "/store/accounts/92-days-ago",
    RETENTION_SAVE: "/retention/save",
    RETENTION_REPORT: "/import/retentionReport",
    RETENTION_SUGGESTIONS: "/import/retention-grouped-suggestions",
    RTPOS_REPORT: "/eodReport/viewRtposReport",
    ASSURANT: {
        SAVE_CLAIM: "/assurant/saveClaim",
        RECEIVE: "/assurant/receive",
        UPLOAD_LABEL: "/assurant/uploadReturnLabelPdf",
        RETURN: "/assurant/return",
        STATUS: "/store/viewAssurantDevicesStatus",
    },
};
