export const API_ROUTES = {
    CREATE_COMPANY: "/admin/companyRegistration",
    GET_COMPANIES: "/admin/companies",
    VIEW_ALL_COMPANIES: "/admin/viewAllCompanies",
    FILE_EXPORT_UPLOADS: {
        activation: "/import/activationDetailReport",
        saleDetail: "/import/saleDetailReport",
        callidus: "/import/callidusReport",
        retentionReport: "/import/retentionReport",
    },
    LAST_UPLOADED_REPORTS: "/import/lastUploadedReportsForCompany",
    VIEW_REBATES: "/import/viewRebates",
    WEEKLY_REBATES_SUMMARY: "/import/weekly-summary",
    RETENTION_COMPANY: "/import/accounts/92-days-ago",
    RETENTION_STORE: "/store/accounts/92-days-ago",
    RETENTION_SAVE: "/retention/save",
    RETENTION_REPORT: "/import/retentionReport",
    RETENTION_SUGGESTIONS: "/import/retention-grouped-suggestions",
    REPORT_UPLOAD_SUGGESTIONS: "/admin/company/report-upload-suggestions",
    DEALER_INVENTORY_COMMISSION: {
        SAVE: "/dealer-inventory-commission/save",
        UPDATE: "/dealer-inventory-commission/update",
        GET: "/dealer-inventory-commission/view",
    },
    RTPOS_REPORT: "/eodReport/viewRtposReport",
    ASSURANT: {
        SAVE_CLAIM: "/assurant/saveClaim",
        RECEIVE: "/assurant/receive",
        UPLOAD_LABEL: "/assurant/uploadReturnLabelPdf",
        RETURN: "/assurant/return",
        STATUS: "/store/viewAssurantDevicesStatus",
    },
    COMPANY_ASSURANT_STATUS: "/company/viewAssurantDevicesStatus",
    COMPANY_RETURN_DEVICES: "/company/viewReturnDevices",
    CUSTOMER_RETURN: {
        SAVE: "/returnPhone/save",
        VIEW: "/returnPhone/inStoreView",
    },
    MAGENTA: {
        SAVE: "/magenta/save",
        ORDER_COMPLETED: "/magenta/orderCompleted",
        ORDER_CANCELLATION: "/magenta/orderCancellation",
        IN_STORE_VIEW: "/magenta/inStoreView",
        COMPANY_VIEW: "/company/viewMagentaOrders",
    },
};
